[model]
type = "seqdistmodel"
package = "bonito.transformer"

[scaling]
strategy = "pa"

[run_info]
sample_type = "dna"
sample_rate = 5000

[standardisation]
standardise = 1
mean = 93.69239463939118
stdev = 23.506745239082388

[qscore]
scale = 1.05
bias = 1.3

[training_dataset]
hash = "12e7fe4713f69f748f4ebc2d777a9ca7bc7a333ad8f376d3c18154fc336c6f00"

[model.seqdist]
state_len = 5
alphabet = [ "N", "A", "C", "G", "T",]

[model.encoder]
type = "namedserial"

[model.encoder.conv]
type = "serial"
[[model.encoder.conv.sublayers]]
type = "convolution"
insize = 1
size = 64
bias = true
winlen = 5
stride = 1
padding = 2
activation = "swish"
norm = "batchnorm"

[[model.encoder.conv.sublayers]]
type = "convolution"
insize = 64
size = 64
bias = true
winlen = 5
stride = 1
padding = 2
activation = "swish"
norm = "batchnorm"

[[model.encoder.conv.sublayers]]
type = "convolution"
insize = 64
size = 128
bias = true
winlen = 9
stride = 3
padding = 4
activation = "swish"
norm = "batchnorm"

[[model.encoder.conv.sublayers]]
type = "convolution"
insize = 128
size = 128
bias = true
winlen = 9
stride = 2
padding = 4
activation = "swish"
norm = "batchnorm"

[[model.encoder.conv.sublayers]]
type = "convolution"
insize = 128
size = 512
bias = true
winlen = 5
stride = 2
padding = 2
activation = "swish"
norm = "batchnorm"

[[model.encoder.conv.sublayers]]
type = "permute"
dims = [ 0, 2, 1,]

[model.encoder.transformer_encoder]
type = "stack"
depth = 18

[model.encoder.upsample]
type = "linearupsample"
d_model = 512
scale_factor = 2

[model.encoder.crf]
type = "linearcrfencoder"
insize = 512
n_base = 4
state_len = 5
bias = false
scale = 5.0
blank_score = 2.0
expand_blanks = true
permute = [ 1, 0, 2,]

[model.encoder.transformer_encoder.layer]
type = "transformerencoderlayer"
d_model = 512
nhead = 8
dim_feedforward = 2048
deepnorm_alpha = 2.4494897
deepnorm_beta = 0.2886751
attn_window = [ 127, 128,]
