[model]
package = "bonito.crf"

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[global_norm]
state_len = 5

[encoder]
type = "serial"
[[encoder.sublayers]]
type = "convolution"
insize = 1
size = 16
bias = true
winlen = 5
stride = 1
padding = 2
activation = "swish"
norm = "batchnorm"

[[encoder.sublayers]]
type = "clamp"
min = -0.5
max = 3.5

[[encoder.sublayers]]
type = "convolution"
insize = 16
size = 16
bias = true
winlen = 5
stride = 1
padding = 2
activation = "swish"
norm = "batchnorm"

[[encoder.sublayers]]
type = "clamp"
min = -0.5
max = 3.5

[[encoder.sublayers]]
type = "convolution"
insize = 16
size = 1024
bias = true
winlen = 19
stride = 6
padding = 9
activation = "swish"
norm = "batchnorm"

[[encoder.sublayers]]
type = "clamp"
min = -0.5
max = 3.5

[[encoder.sublayers]]
type = "permute"
dims = [ 2, 0, 1,]

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 1

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 0

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 1

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 0

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 1

[[encoder.sublayers]]
type = "linear"
in_features = 1024
out_features = 256

[[encoder.sublayers]]
type = "linearcrfencoder"
insize = 256
n_base = 4
state_len = 5
bias = false
blank_score = 2.0

[[encoder.sublayers]]
type = "clamp"
min = -5.0
max = 5.0

[qscore]
scale = 0.95
bias = 0.5

[basecaller]
batchsize = 96
chunksize = 10000
overlap = 500

[training]
command = "train"
training_directory = "/projects/agalbraith_prj/bonito/models/dna_r10.4.1_e8.2_400bps_sup_@v4.2.0_OxoG_finetune_new"
config = "/projects/agalbraith_prj/software/bonito/bonito/models/configs/dna_r9.4.1@v3.1.toml"
pretrained = "/projects/agalbraith_prj/software/bonito/bonito/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0"
directory = "PosixPath('/projects/agalbraith_prj/bonito/bonito_train_basecaller/5000Hz_merge')"
device = "cuda:0"
lr = "5e-4"
seed = 25
epochs = 1
batch = 32
chunks = 0
no_amp = false
force = true
restore_optim = false
nondeterministic = false
save_optim_every = 10
grad_accum_split = 1
quantile_grad_clip = false
func = "<function main at 0x150a2a14e680>"
